lxc/caps.h: typo lxc_bounding_as_ambiant_caps
Building lxc results in a build failure:

    src/lxc/attach.c: In function ‘do_attach’:
    src/lxc/attach.c:1379:23: error:
    implicit declaration of function ‘lxc_bounding_as_ambient_caps’;
    did you mean ‘lxc_bounding_as_ambiant_caps’?
    [-Wimplicit-function-declaration]
     1379 |                 ret = lxc_bounding_as_ambient_caps();
          |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
          |                       lxc_bounding_as_ambiant_caps

Rename lxc_bounding_as_ambiant_caps() to lxc_bounding_as_ambient_cap()
to match the rest of the code.

Fixes:f378e2ea11cb ("keep capabilities if init process is not run as root")

Signed-off-by: Heinrich Schuchardt <heinrich.schuchardt@canonical.com>